# Generated by Django 4.0.4 on 2022-06-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academy_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_name', models.CharField(max_length=30)),
                ('ac_yr', models.CharField(max_length=4)),
                ('ac_contact', models.CharField(max_length=12)),
                ('ac_info', models.CharField(max_length=100)),
                ('ac_city', models.CharField(max_length=30)),
                ('ac_website', models.CharField(max_length=30)),
                ('ac_logo', models.CharField(max_length=100)),
                ('ac_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academy_tbl',
            },
        ),
        migrations.CreateModel(
            name='doubt_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtitle', models.CharField(max_length=100)),
                ('ddesc', models.CharField(max_length=500)),
                ('dtype', models.CharField(default=0, max_length=20)),
                ('ddate', models.DateField(auto_now_add=True)),
                ('dstatus', models.CharField(max_length=10)),
                ('dthumb', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=20, null=True)),
                ('cagr', models.CharField(max_length=20, null=True)),
                ('target', models.CharField(max_length=20, null=True)),
                ('stock', models.CharField(max_length=20, null=True)),
                ('exchange', models.CharField(max_length=20, null=True)),
                ('deadline', models.DateField(default=None, null=True)),
                ('risk', models.CharField(max_length=20, null=True)),
                ('capital', models.CharField(max_length=20, null=True)),
                ('sector', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'doubt_tbl',
            },
        ),
        migrations.CreateModel(
            name='login_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unemail', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'login_tbl',
            },
        ),
        migrations.CreateModel(
            name='package_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(max_length=30)),
                ('pkg_description', models.CharField(max_length=300)),
                ('pkg_duration', models.CharField(max_length=4)),
                ('pkg_datetime', models.DateTimeField(auto_now_add=True)),
                ('pkg_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('pkg_thumb', models.CharField(max_length=20)),
                ('pkg_language', models.CharField(max_length=20)),
                ('pkg_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academy_tbl')),
            ],
            options={
                'db_table': 'package_tbl',
            },
        ),
        migrations.CreateModel(
            name='stockdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'stockdata',
            },
        ),
        migrations.CreateModel(
            name='useractivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('sector', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('revenueGrowth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommendationKey', models.CharField(max_length=50)),
                ('last_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl')),
            ],
            options={
                'db_table': 'useractivity',
            },
        ),
        migrations.CreateModel(
            name='user_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('ContactNo', models.CharField(max_length=12)),
                ('ExperienceYr', models.CharField(max_length=2)),
                ('Profession', models.CharField(max_length=30)),
                ('trdr_type', models.CharField(max_length=30)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl')),
            ],
            options={
                'db_table': 'user_tbl',
            },
        ),
        migrations.CreateModel(
            name='tutor_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_name', models.CharField(max_length=30)),
                ('tu_exp', models.CharField(max_length=4)),
                ('tu_cons', models.CharField(max_length=4)),
                ('tu_contact', models.CharField(max_length=12)),
                ('tu_desc', models.CharField(max_length=100)),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl')),
                ('tu_acid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.academy_tbl')),
            ],
            options={
                'db_table': 'tutor_tbl',
            },
        ),
        migrations.CreateModel(
            name='tradebook_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('b_date', models.DateField()),
                ('s_date', models.DateField()),
                ('buy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gain', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('strategy', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('nodays', models.IntegerField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl')),
            ],
            options={
                'db_table': 'tradebook_tbl',
            },
        ),
        migrations.CreateModel(
            name='solution_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=500)),
                ('sdate', models.DateField(auto_now_add=True)),
                ('link', models.CharField(max_length=30)),
                ('doubt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doubt_tbl')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tutor_tbl')),
                ('ulogin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl')),
            ],
            options={
                'db_table': 'solution_tbl',
            },
        ),
        migrations.CreateModel(
            name='pkgfeature_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_feature', models.CharField(max_length=50)),
                ('pf_acid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academy_tbl')),
                ('pf_pkg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.package_tbl')),
            ],
            options={
                'db_table': 'pkgfeature_tbl',
            },
        ),
        migrations.AddField(
            model_name='package_tbl',
            name='pkg_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutor_tbl'),
        ),
        migrations.CreateModel(
            name='loginactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logintime', models.DateTimeField(auto_now_add=True)),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl')),
            ],
            options={
                'db_table': 'loginactivity',
            },
        ),
        migrations.AddField(
            model_name='doubt_tbl',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl'),
        ),
        migrations.CreateModel(
            name='blog_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=100)),
                ('bsub', models.CharField(max_length=100)),
                ('bstatus', models.BooleanField(default=True)),
                ('bdate', models.DateField(auto_now_add=True)),
                ('bdesc', models.CharField(max_length=500)),
                ('bthumb', models.CharField(max_length=100)),
                ('b_acid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.academy_tbl')),
                ('b_tid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tutor_tbl')),
            ],
            options={
                'db_table': 'blog_tbl',
            },
        ),
        migrations.AddField(
            model_name='academy_tbl',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl'),
        ),
    ]
