# Generated by Django 4.0.4 on 2022-06-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter_tbl',
            name='ch_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter_tbl',
            name='ch_pdftitle',
            field=models.CharField(default='No Title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter_tbl',
            name='ch_videotitle',
            field=models.CharField(default='No Title', max_length=100),
            preserve_default=False,
        ),
    ]
