# Generated by Django 4.0.4 on 2022-06-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_no', models.IntegerField()),
                ('u_title', models.CharField(max_length=50)),
                ('u_description', models.CharField(max_length=50)),
                ('u_content', models.CharField(max_length=100)),
                ('u_pkg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.package_tbl')),
            ],
            options={
                'db_table': 'unit_tbl',
            },
        ),
    ]
