# Generated by Django 4.0.1 on 2022-02-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='package_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(max_length=30)),
                ('pkg_duration', models.CharField(max_length=4)),
                ('pkg_thumb', models.CharField(max_length=100)),
                ('pkg_price', models.CharField(max_length=10)),
                ('pkg_desc', models.CharField(max_length=100)),
                ('p_acid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academy_tbl')),
            ],
            options={
                'db_table': 'package_tbl',
            },
        ),
        migrations.CreateModel(
            name='tutor_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_name', models.CharField(max_length=30)),
                ('tu_exp', models.CharField(max_length=4)),
                ('tu_cons', models.CharField(max_length=4)),
                ('tu_contact', models.CharField(max_length=12)),
                ('tu_desc', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl')),
                ('tu_acid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academy_tbl')),
            ],
            options={
                'db_table': 'tutor_tbl',
            },
        ),
        migrations.CreateModel(
            name='pkgfeature_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_feature', models.CharField(max_length=50)),
                ('pf_acid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academy_tbl')),
                ('pf_pkgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.package_tbl')),
            ],
            options={
                'db_table': 'pkgfeature_tbl',
            },
        ),
    ]
