# Generated by Django 4.0.4 on 2022-06-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chapter_tbl_ch_no_chapter_tbl_ch_pdftitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_tbl',
            old_name='course_datetime',
            new_name='course_date',
        ),
        migrations.RenameField(
            model_name='unit_tbl',
            old_name='u_pkg',
            new_name='u_course',
        ),
        migrations.RemoveField(
            model_name='unit_tbl',
            name='u_description',
        ),
        migrations.AddField(
            model_name='subscription_tbl',
            name='user_review',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
