# Generated by Django 4.0.1 on 2022-01-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_login_tbl_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tbl',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl'),
            preserve_default=False,
        ),
    ]
