# Generated by Django 4.0.4 on 2022-06-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_unit_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_note', models.CharField(max_length=300)),
                ('ch_pdf', models.CharField(max_length=100)),
                ('ch_video', models.CharField(max_length=100)),
                ('ch_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unit_tbl')),
            ],
            options={
                'db_table': 'chapter_tbl',
            },
        ),
    ]
