# Generated by Django 4.0.1 on 2022-02-20 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_package_tbl_tutor_tbl_pkgfeature_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy_tbl',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl'),
        ),
        migrations.CreateModel(
            name='tradebook_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('b_date', models.DateField()),
                ('s_date', models.DateField()),
                ('buy', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sell', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pnl', models.DecimalField(decimal_places=3, max_digits=10)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl')),
            ],
            options={
                'db_table': 'tradebook_tbl',
            },
        ),
    ]
