# Generated by Django 4.0.1 on 2022-02-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_academy_tbl_login_tradebook_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy_tbl',
            name='ac_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
