# Generated by Django 4.0.1 on 2022-01-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_tbl_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tbl',
            name='Email',
        ),
    ]
