# Generated by Django 4.0.4 on 2022-06-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chapter_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_tbl',
            name='pkg_thumb',
            field=models.CharField(max_length=100),
        ),
    ]
