# Generated by Django 4.0.1 on 2022-02-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_tbl_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='academy_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_name', models.CharField(max_length=30)),
                ('ac_yr', models.CharField(max_length=4)),
                ('ac_contact', models.CharField(max_length=12)),
                ('ac_info', models.CharField(max_length=12)),
                ('ac_city', models.CharField(max_length=12)),
                ('ac_website', models.CharField(max_length=12)),
            ],
        ),
    ]
