# Generated by Django 4.0.1 on 2022-02-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_academy_tbl_ac_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradebook_tbl',
            name='gain',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tradebook_tbl',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tradebook_tbl',
            name='strategy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
