# Generated by Django 4.0.1 on 2022-02-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tradebook_tbl_gain_tradebook_tbl_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradebook_tbl',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradebook_tbl',
            name='pnl',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradebook_tbl',
            name='sell',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
