# Generated by Django 4.0.1 on 2022-02-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_academy_tbl_ac_city_alter_academy_tbl_ac_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy_tbl',
            name='ac_logo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academy_tbl',
            name='ac_info',
            field=models.CharField(max_length=100),
        ),
    ]
