# Generated by Django 4.0.1 on 2022-02-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_tutor_tbl_login_alter_tutor_tbl_tu_acid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doubt_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtitle', models.CharField(max_length=100)),
                ('ddesc', models.CharField(max_length=500)),
                ('ddate', models.DateField(auto_now_add=True)),
                ('dstatus', models.CharField(max_length=10)),
                ('dthumb', models.CharField(max_length=100)),
                ('servicetag', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=20)),
                ('exchange', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
                ('risk', models.CharField(max_length=20)),
                ('capital', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'doubt_tbl',
            },
        ),
    ]
