# Generated by Django 4.0.1 on 2022-02-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_academy_tbl_ac_logo_alter_academy_tbl_ac_info'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academy_tbl',
            table='academy_tbl',
        ),
    ]
