# Generated by Django 4.0.4 on 2022-06-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_course_tbl_course_ac'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_tbl',
            name='course_ac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.academy_tbl'),
        ),
    ]
