# Generated by Django 4.0.4 on 2022-06-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_course_tbl_course_ac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefeature_tbl',
            name='cf_acid',
        ),
        migrations.RemoveField(
            model_name='coursefeature_tbl',
            name='cf_course',
        ),
        migrations.RemoveField(
            model_name='subscription_tbl',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subscription_tbl',
            name='user',
        ),
    ]
