# Generated by Django 4.0.1 on 2022-02-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_doubt_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt_tbl',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl'),
        ),
        migrations.CreateModel(
            name='solution_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=500)),
                ('sdate', models.DateField(auto_now_add=True)),
                ('link', models.CharField(max_length=30)),
                ('doubt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doubt_tbl')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl')),
            ],
            options={
                'db_table': 'solution_tbl',
            },
        ),
    ]
