# Generated by Django 4.0.1 on 2022-02-14 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_academy_tbl_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy_tbl',
            name='ac_date',
            field=models.DateField(default=datetime.date),
            preserve_default=False,
        ),
    ]
