# Generated by Django 4.0.1 on 2022-02-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_academy_tbl_ac_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy_tbl',
            name='ac_packagecount',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academy_tbl',
            name='ac_tutorcount',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
