# Generated by Django 4.0.4 on 2022-06-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_coursefeature_tbl_cf_acid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeature_tbl',
            name='cf_acid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.academy_tbl'),
        ),
        migrations.AddField(
            model_name='coursefeature_tbl',
            name='cf_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course_tbl'),
        ),
        migrations.AddField(
            model_name='subscription_tbl',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course_tbl'),
        ),
        migrations.AddField(
            model_name='subscription_tbl',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user_tbl'),
        ),
        migrations.AlterField(
            model_name='chapter_tbl',
            name='ch_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.unit_tbl'),
        ),
        migrations.AlterField(
            model_name='unit_tbl',
            name='u_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course_tbl'),
        ),
    ]
