# Generated by Django 4.0.1 on 2022-02-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_doubt_id_solution_tbl_doubt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubt_tbl',
            name='servicetag',
        ),
        migrations.AddField(
            model_name='doubt_tbl',
            name='cagr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doubt_tbl',
            name='target',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doubt_tbl',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solution_tbl',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tutor_tbl'),
        ),
    ]
