# Generated by Django 4.0.4 on 2022-06-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_coursefeature_tbl_cf_acid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_tbl',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='subscription_tbl',
            name='user_review',
        ),
        migrations.CreateModel(
            name='courserating_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('user_review', models.CharField(max_length=150, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course_tbl')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user_tbl')),
            ],
            options={
                'db_table': 'courserating_tbl',
            },
        ),
    ]
