# Generated by Django 4.0.1 on 2022-02-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_academy_tbl_ac_packagecount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy_tbl',
            name='ac_date',
        ),
    ]
