# Generated by Django 4.0.1 on 2022-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_doubt_tbl_dtype_alter_doubt_tbl_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt_tbl',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
