# Generated by Django 4.0.1 on 2022-02-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_doubt_tbl_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt_tbl',
            name='deadline',
            field=models.DateField(default=None, null=True),
        ),
    ]
