# Generated by Django 4.0.1 on 2022-02-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_doubt_tbl_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt_tbl',
            name='dtype',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
