# Generated by Django 4.0.1 on 2022-02-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_doubt_tbl_dtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution_tbl',
            name='ulogin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl'),
        ),
    ]
