# Generated by Django 4.0.4 on 2022-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_solution_tbl_ulogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
