# Generated by Django 4.0.4 on 2022-05-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_stockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradebook_tbl',
            name='no_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
