# Generated by Django 4.0.4 on 2022-05-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_tradebook_tbl_no_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tbl',
            name='trdr_type',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_tbl',
            name='type',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
