# Generated by Django 4.0.4 on 2022-05-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_user_tbl_trdr_type_user_tbl_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradebook_tbl',
            name='no_days',
        ),
    ]
