# Generated by Django 4.0.4 on 2022-05-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_tradebook_tbl_no_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradebook_tbl',
            name='nodays',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
