# Generated by Django 4.0.4 on 2022-05-31 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_tradebook_tbl_nodays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tbl',
            name='type',
        ),
    ]
