# Generated by Django 4.0.4 on 2022-06-06 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_user_tbl_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockdata',
            table='stockdata',
        ),
        migrations.CreateModel(
            name='useractivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('sector', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=20)),
                ('revenueGrowth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommendationKey', models.CharField(max_length=20)),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl')),
            ],
            options={
                'db_table': 'useractivity',
            },
        ),
        migrations.CreateModel(
            name='loginactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logintime', models.DateTimeField(auto_now_add=True)),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login_tbl')),
            ],
            options={
                'db_table': 'loginactivity',
            },
        ),
    ]
