# Generated by Django 4.0.4 on 2022-06-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_stockdata_table_useractivity_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
