# Generated by Django 4.0.4 on 2022-06-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_useractivity_last_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
