# Generated by Django 4.0.4 on 2022-06-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_useractivity_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy_tbl',
            name='ac_packagecount',
        ),
        migrations.RemoveField(
            model_name='academy_tbl',
            name='ac_tutorcount',
        ),
    ]
