# Generated by Django 4.0.4 on 2022-06-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_academy_tbl_ac_packagecount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package_tbl',
            old_name='p_acid',
            new_name='p_ac',
        ),
        migrations.RenameField(
            model_name='pkgfeature_tbl',
            old_name='pf_pkgid',
            new_name='pf_pkg',
        ),
    ]
